(**
 * Machine IR.
 * A pseudo-x86-64 machine IR, to be generated by the instruction selection pass.
 *)

open! Core

type sym = Label.sym
type label = Label.t
type vreg = Reg.vreg
type preg = Reg.preg
type reg = Reg.reg

type mem_addr =
  | Static of label
  | Dynamic of
      { base : reg
      ; offset : int
      }

type operand =
  | Imm32 of Int32.t
  | Reg of reg
  | Addr of mem_addr
  | Sym of sym

type program =
  { data : sym list
  ; code : block list
  }

and block =
  { label : label
  ; data : liveness list
  }

and liveness =
  { instr : minstr
  ; uses : reg Hash_set.t
  ; defs : reg Hash_set.t
  ; clobbers : reg Hash_set.t
  }

and minstr =
  | Mov of
      { dst : vreg
      ; src : operand
      }
  | Add of
      { dst : vreg
      ; src : operand
      }
  | Sub of
      { dst : vreg
      ; src : operand
      }
  | IMul of
      { dst : vreg
      ; src : operand
      }
  | IDiv of
      { quot : vreg
      ; rem : vreg
      ; dividend : operand
      ; divisor : operand
      }
  | Neg of { dst : vreg }
  | Not of { dst : vreg }
  | Call of operand
  | Jmp of label
  | Je of label
  | Jne of label
  | Jl of label
  | Jle of label
  | Jg of label
  | Jge of label
  | Sete of reg
  | Setne of reg
  | Setl of reg
  | Setle of reg
  | Setg of reg
  | Setge of reg
  | Ret
